name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: run linters
        uses: ./.github/actions/run-linters
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Test Report
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: ${{ !cancelled() }}
        with:
          name: Unit tests
          path: reports/jest-*.xml
          reporter: jest-junit
